openapi: 3.0.1
info:
  title: Booking API
  version: 1.0.0
  description: API for managing bookings
servers:
  - url: http://localhost:3002
    description: Local Development Environment
paths:
  /booking:
    get:
      operationId: getAllBookings
      summary: Retrieve all bookings with pagination
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for paginated results (default is 1)
        - name: count
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 10
          description: Number of bookings per page (default is 10)
      responses:
        "200":
          description: Successfully retrieved paginated bookings
          content:
            application/json:
              schema:
                type: object
                properties:
                  bookings:
                    type: array
                    items:
                      $ref: "#/components/schemas/Booking"
                  total:
                    type: integer
                    description: Total number of bookings
                  page:
                    type: integer
                    description: Current page number
                  count:
                    type: integer
                    description: Number of bookings per page
        "400":
          description: Bad Request - Invalid query parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - Insufficient permissions to access resource
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: initiateBooking
      summary: Create a new booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Booking"
      responses:
        "201":
          description: Booking created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Booking"
        "400":
          description: Bad Request - Invalid input data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - Insufficient permissions to create resource
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /booking/{id}:
    get:
      operationId: getBookingById
      summary: Retrieve a booking by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for the booking
      responses:
        "200":
          description: Successfully retrieved booking
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Booking"
        "400":
          description: Bad Request - Invalid ID format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - Insufficient permissions to view this resource
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Booking not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      operationId: cancelBooking
      summary: Cancel an existing booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Booking"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for the booking
      responses:
        "200":
          description: Booking cancelled successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Booking"
        "400":
          description: Bad Request - Invalid ID or request body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - Insufficient permissions to update this resource
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Booking not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Booking:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the booking
        user_id:
          type: string
          description: Identifier for the user who created the booking
        service_id:
          type: string
          description: Identifier for the service being booked
        status:
          type: string
          description: Current status of the booking
          enum:
            - pending
            - confirmed
            - cancelled
        created_at:
          type: string
          format: date-time
          description: Booking creation timestamp
    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
