openapi: 3.0.1
info:
  title: Service API
  description: API for managing services
  version: 1.0.0
servers:
  - url: http://localhost:3002
    description: Local development environment

paths:
  /service:
    post:
      summary: Create a new service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                service_provider_id:
                  type: string
                  description: Refers to ServiceProviderProfile
                name:
                  type: string
                  description: Name of the service
                description:
                  type: string
                  description: Description of the service
                price:
                  type: number
                  format: float
                  description: Price of the service
                duration:
                  type: string
                  description: Duration of the service
      responses:
        '200':
          description: Service created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        '400':
          description: Bad Request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - Insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Get all services
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: Page number of the results to retrieve
        - name: count
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Number of results per page
      responses:
        '200':
          description: List of all services
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_items:
                    type: integer
                    description: Total number of services available
                  total_pages:
                    type: integer
                    description: Total number of pages available
                  current_page:
                    type: integer
                    description: Current page number
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Service'
        '400':
          description: Bad Request - Invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - Insufficient permissions to access resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: No services found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /service/{id}:
    get:
      summary: Get a specific service by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the service to retrieve
      responses:
        '200':
          description: Service details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        '400':
          description: Bad Request - Invalid ID format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - Insufficient permissions to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Service not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update an existing service
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the service to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                  format: float
                duration:
                  type: string
      responses:
        '200':
          description: Service updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        '400':
          description: Bad Request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - Insufficient permissions to update this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Service not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    patch:
      summary: Partially update a specific service
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the service to partially update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the service
                description:
                  type: string
                  description: Description of the service
                price:
                  type: number
                  format: float
                  description: Price of the service
                duration:
                  type: string
                  description: Duration of the service
      responses:
        '200':
          description: Service partially updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        '400':
          description: Bad Request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - Insufficient permissions to update this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Service not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a specific service by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the service to delete
      responses:
        '200':
          description: Service deleted successfully
        '400':
          description: Bad Request - Invalid ID format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - Insufficient permissions to delete this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Service not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Service:
      type: object
      properties:
        id:
          type: integer
          description: UUID Primary key
        service_provider_id:
          type: string
          description: Refers to ServiceProviderProfile
        name:
          type: string
          description: Name of the service
        description:
          type: string
          description: Description of the service
        price:
          type: number
          format: float
          description: Price of the service
        duration:
          type: string
          description: Duration of the service

    Error:
      type: object
      properties:
        code:
          type: integer
          description: Error code
        message:
          type: string
          description: Error message
