openapi: 3.0.1
info:
  title: Service Provider API
  version: 1.0.0
  description: API for managing service provider details
servers:
  - url: http://localhost:3002
    description: Local Development Environment
paths:
  /service-providers:
    get:
      operationId: search-service-providers
      summary: Get a list of all service providers
      responses:
        "200":
          description: Successfully retrieved list of service providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ServiceProvider"
        "400":
          description: Bad Request - Invalid query or parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - Insufficient permissions to access resource
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a new service provider
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServiceProvider"
      responses:
        "201":
          description: Service provider created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceProvider"
        "400":
          description: Bad Request - Invalid input data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - Insufficient permissions to create resource
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /service-providers/{service_provider_id}:
    get:
      operationId: get-service-provider
      summary: Get a specific service provider by ID
      parameters:
        - name: service_provider_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully retrieved service provider details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceProvider"
        "400":
          description: Bad Request - Invalid ID format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - Insufficient permissions to view this resource
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Service provider not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      summary: Update a specific service provider
      parameters:
        - name: service_provider_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServiceProvider"
      responses:
        "200":
          description: Service provider updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceProvider"
        "400":
          description: Bad Request - Invalid input data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - Insufficient permissions to update this resource
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Service provider not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      summary: Partially update a specific service provider
      parameters:
        - name: service_provider_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServiceProvider"
      responses:
        "200":
          description: Service provider updated successfully with partial data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceProvider"
        "400":
          description: Bad Request - Invalid input data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - Insufficient permissions to update this resource
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Service provider not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Delete a specific service provider
      parameters:
        - name: service_provider_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Service provider deleted successfully
        "401":
          description: Authentication Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - Insufficient permissions to delete this resource
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Service provider not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    ServiceProvider:
      type: object
      properties:
        user_id:
          type: integer
          description: References the user table
        business_name:
          type: string
          description: Name of the business
        service_types:
          type: object
          description: Service types provided by the business
          example: { "type1": "Cleaning", "type2": "Plumbing" }
        hourly_rate:
          type: number
          format: float
          description: Default rate per hour
        availability_id:
          type: integer
          description: References availability information
        ranking_payment:
          type: number
          format: float
          description: Ranking payment made for search ranking
        is_premium:
          type: boolean
          description: Boolean for a premium user
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
